# Open PHACTS platform
# Docker Compose customization
# https://docs.docker.com/compose/yml/
#
# This file is meant to override docker-compose.yml
# with any customizations. Thus you should not need
# to modify docker-compose.yml directly.

# Uncomment settings below you want to customize:

explorer:
  environment:
    # CHANGE: "localhost" to fully qualified hostname
    # Do NOT include a trailing /
    #- API_URL=http://example.com:3002
  #restart: always

api:
  #environment:
  #  - CRS=https://ops.rsc.org/api/v1/
  #  - CONCEPTWIKI=http://www.conceptwiki.org/web-ws/concept
  #restart: always

# SPARQL server
virtuoso:
  #restart: always

virtuosodata:
  volumes:
    # To specify alternative data folder, use instad:
    #- /media/big-SSD/virtuoso:/virtuoso

mysqldata:
  image: busybox
    # To specify alternative data folder, use instead:
    # - /media/big-SSD/mysql:/var/lib/mysql

virtuosostaging:
  volumes:
    #- /media/big-SSD/staging:/staging
    #- /media/big-SSD/download:/download


mysql:
  #restart: always

ims:
  #restart: always

memcached:
  #restart: always
